name: ci-to-aws

on:
  push:
    branches: ["main", feature/*]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build Lambda packages
        run: |
          apt-get update
          apt-get install awscli
          npm install -g pnpm

          echo "Bulding Lambda."
                   
          #Build source code in zip files
          cd ./lambda-source
          echo "Building lambda"
          pnpm install
          zip -r build.zip ./* --quiet
          cd ../../

      - name: Upload Lambda packages
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          LAMBDA_BUCKET: ${{ secrets.LAMBDA_BUCKET }}
          LAMBDA_FUNCTION: ${{ secrets.LAMBDA_FUNCTION }}

        run: |

          echo "Uploading lambdas to S3."

          # build source code in zip files
          cd ./lambda-source
          echo "Uploading lambda"

          # Upload to s3
          aws s3 cp ./build.zip s3://${LAMBDA_BUCKET}/build.zip

          # Update Lambda Function
          aws lambda update-function-code --function-name learning-warehouse --s3-bucket ${LAMBDA_BUCKET} --s3-key build.zip

          cd ../../
